### ISSUE TITLE
Activecode output not displaying whatsoever

### ISSUE THREAD

**Issue by mattteahan3200** [RunestoneInteractive/rs#678]
**What Course are you in**
How to Think like a Computer Scientist

**What Page were you on**
2.13, issue appearing on all pages

**What is your username**
mattteahan3200

**Describe the bug**
Activecode output does not appear when "Save & Run" is pressed. It only displays this below the editable activecode window "Active Code (httlacs_2_ch02_ex1". There is no grey box with the output that should show up. 

Multiple browsers have been tested with the same issue. 

**Traceback**
N/A

**Javascript Errors**
N/A

**Comment by bnmnetp** [comment]
Sorry about that. I was making some changes to improve accessibility.  It was working locally but appeared to break a bunch of books in production.  Should be fixed now.

**Comment by mattteahan3200** [comment]
Activecode is still not working FYI. Let me know if any updates are made, thanks!

**Comment by bnmnetp** [comment]
Make sure you try a hard refresh.  I've just tried it in multiple browsers.  Whereas I can confirm the problem you reported was happening for me as well, I have fixed the problem and rebuilt all the books and it is working across all books.

**Comment by bnmnetp** [comment]
It may also have been a cache issue with CloudFlare.  I have purged the cache to ensure everyone is getting the right version.
